### ISSUE TITLE
Off by one error on value returned from read() ?

### ISSUE THREAD

**Issue by totalspectrum** [ironsheep/P2-FLASH-FS#2]
### and have you...

- [X] I updated to the latest version available
- [X] My code conforms to calling sequences shown in demo code

### Version of P2 Flash FS

Tested in latest github sources

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### P2 Hardware, Compiler used

P2 Board: P2 Eval Board
P2 Compiler: both flexspin and PNut v39

### Description of problem

Read seems to return 1 byte more than the requested number of bytes. For example:
```
CON
  _clkfreq = 250_000_000

OBJ
  flash: "flash_fs"

DAT
buf	BYTE 128

PUB demo() | r, handle
  flash.mount()
  handle := flash.open(@"rwblocks.bin", "r")
  if handle >= 0
    r := flash.read(handle, @buf[0], 32)
    debug("requested 32 bytes, read returned ", sdec_(r))
    flash.close(handle)
  flash.unmount()
```
outputs:
```
Cog0  requested 32 bytes, read returned 33
```

**Comment by ironsheep** [comment]
Fascinating...  I've done hundreds of 88 byte and 1024 byte reads in my regression tests, no errors.

see RT_read_write_block_tests.spin2 and RT_read_write_circular_tests.spin2.  These regressions tests all passed.

I'm adding tests similar to what you've done herein.  And I'll make sure that's working...

**Comment by ironsheep** [comment]
ok, not seeing the failure.  My new regression test output:

Cog0  * Test #95: read 20 N-length groups of bytes
Cog0    -- Read #1 17 byte(s) - pass
Cog0    -- Read #2 28 byte(s) - pass
Cog0    -- Read #3 2 byte(s) - pass
Cog0    -- Read #4 18 byte(s) - pass
Cog0    -- Read #5 25 byte(s) - pass
Cog0    -- Read #6 1 byte(s) - pass
Cog0    -- Read #7 16 byte(s) - pass
Cog0    -- Read #8 17 byte(s) - pass
Cog0    -- Read #9 7 byte(s) - pass
Cog0    -- Read #10 28 byte(s) - pass
Cog0    -- Read #11 20 byte(s) - pass
Cog0    -- Read #12 6 byte(s) - pass
Cog0    -- Read #13 26 byte(s) - pass
Cog0    -- Read #14 15 byte(s) - pass
Cog0    -- Read #15 24 byte(s) - pass
Cog0    -- Read #16 29 byte(s) - pass
Cog0    -- Read #17 28 byte(s) - pass
Cog0    -- Read #18 14 byte(s) - pass
Cog0    -- Read #19 8 byte(s) - pass
Cog0    -- Read #20 16 byte(s) - pass
Cog0    Sub-Test Results: Pass: 40, Fail: 0

This validates both the flash.error() == flash.SUCCESS and that the length passed to read is the returned number of bytes  read.

I'm committing the regression test changes to the repo as well as the logs from this run.
I've run these tests against the newly releasing version v1.3.0

**Comment by totalspectrum** [comment]
Which version of PNut are you using? I get test failures with both PNut 38 and 39, but not with an earlier PNut. Chip changed the behavior of repeat i from 0 to N-1 a while ago: in the original Spin it left i as N, then in some earlier Spin2s it left i as N-1, and now its back to N again. Flexspin leaves it at N to match the most recent PNut.

**Comment by totalspectrum** [comment]
I've made a PR to make this work with both older and newer PNut. WIth the PR change, all the regression tests pass for flexspin.

**Comment by ironsheep** [comment]
I'm using PNut v39 and PT v2.9.2 upgrading to v2.9.3 before releasing my next version.
